Configurable prop for UI kit components to refetch data
propeldata/ui-kit pull request #93
Opened 2023-07-12 18:06 UTC by felipecadavid

## Description of changes

This PR implements React Query for all the UI Kit components and adds a prop for allowing the user to set a refetch interval

## Checklist

Before merging to main:

- [ ] Tests
- [x] Manually tested in React apps
- [x] Release notes
- [ ] Approved

## Release notes

```md
# Component changes

## Time Series

- Added usage of useTimeSeries hook and ability to provide a refetchInterval prop.

## Leaderboard

- Added usage of useLeaderboard hook and ability to provide a refetchInterval prop.

## Counter

- Added usage of useCounter hook and ability to provide a refetchInterval prop.

# Packages changes

## GraphQL

- Added useCounter, useTimeSeries and useLeaderboard hooks for fetching data.

# App changes

## React sample apps.

- Added a test in every sample app for testing refetchInterval.

## Storybook

- Added Y story for Time Series.
```

2023-07-14 10:41 UTC, markandrus requested changes
We need to use the functionality that GraphQL code generator is already providing us. It will simplify things. Please look at my PR here, and let's build on that: https://github.com/propeldata/ui-kit/pull/97

It still needs the React app changes merged in. Can you please help add those to the PR, and help to test/validate?

2023-07-14 15:46 UTC, felipecadavid commented on app/examples/react-16/src/components/CounterConnectedTest.jsx
> +    setRefetchInterval(refetchInterval ? undefined : 1000)
I think right now there is no difference between the code of each version, I like this idea of having a canonical version of each.

2023-07-14 16:31 UTC, felipecadavid commented on app/examples/react-16/src/components/CounterConnectedTest.jsx
> +    setRefetchInterval(refetchInterval ? undefined : 1000)
> Should this just be refetchInterval ?? 1000, and in all subsequent places, too?

That wouldn't work, here we just want to switch from undefined => 1000 and from 1000 => undefined
`refetchInterval ?? 1000` would set `refetchInterval` to 1000 when it's undefined but wouldn't set it to undefined when it's 1000

2023-07-17 12:45 UTC, markandrus commented
Closed in favor of https://github.com/propeldata/ui-kit/pull/97

2023-07-17 12:45 UTC, closed without merging